/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_grafika_gles_NativeJniCall */

#ifndef _Included_com_android_grafika_gles_GLESNativeTool
#define _Included_com_android_grafika_gles_GLESNativeTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_grafika_gles_NativeJniCall
 * Method:    glReadPixelWithJni
 * Signature: (IIIIIII)V
 */
typedef unsigned char BYTE;

JNIEXPORT void JNICALL Java_com_android_grafika_gles_GLESNativeTool_glReadPixelWithJni
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

JNIEXPORT void  JNICALL Java_com_android_grafika_gles_GLESNativeTool_convertByteBufferToByteArray
  (JNIEnv *, jobject, jobject, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
